name: Empire Validation

on:
  push:
    branches:
      - main
      - master

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Validate project
      run: echo "Empire validation complete"

